import { z } from 'zod';

export const propertySchema = z.object({
  title: z.object({
    en: z.string().min(3).max(200),
    ar: z.string().min(3).max(200),
  }),
  description: z.object({
    en: z.string().max(5000),
    ar: z.string().max(5000),
  }),
  type: z.enum(["apartment", "villa", "townhouse", "office", "warehouse", "land", "penthouse"]),
  category: z.enum(["rent", "sale", "off-plan"]),
  price: z.number().min(0),
  currency: z.enum(["AED", "SAR", "QAR", "USD"]),
  pricePerSqm: z.number().min(0).optional(),
  beds: z.number().min(0).optional(),
  baths: z.number().min(0).optional(),
  area: z.object({
    builtUp: z.number().min(0),
    plot: z.number().min(0).optional(),
    unit: z.enum(["sqm", "sqft"]),
  }),
  yearBuilt: z.number().min(1800).max(new Date().getFullYear()).optional(),
  floors: z.number().min(0).optional(),
  furnishing: z.enum(["furnished", "unfurnished", "partially"]).optional(),
  emirate: z.enum(["Dubai","Abu Dhabi","Sharjah","Ajman","Umm Al Quwain","Ras Al Khaimah","Fujairah"]),
  city: z.string().min(2),
  neighborhood: z.string().optional(),
  location: z.object({
    type: z.literal("Point"),
    coordinates: z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]),
    address: z.object({
      en: z.string().min(5),
      ar: z.string().min(5),
    }),
    emirate: z.enum(["Dubai","Abu Dhabi","Sharjah","Ajman","Umm Al Quwain","Ras Al Khaimah","Fujairah"]),
    city: z.string(),
    neighborhood: z.string().optional(),
    postalCode: z.string().optional(),
  }),
  media: z.array(z.object({
    url: z.string().url(),
    type: z.enum(["image","video","vr"]),
    order: z.number().optional(),
    caption: z.object({ en: z.string().optional(), ar: z.string().optional() }).optional(),
  })).optional(),
  coverImage: z.string().url(),
  floorPlans: z.array(z.object({
    url: z.string().url(),
    caption: z.object({ en: z.string().optional(), ar: z.string().optional() }),
    area: z.number().min(0),
  })).optional(),
  agencyId: z.string().min(24).max(24).optional(),
  commission: z.object({
    percentage: z.number().min(0).max(100),
    fixed: z.number().min(0).optional(),
    paymentTerms: z.string(),
  }),
  reraNumber: z.string().regex(/^RERA-[A-Z0-9]+$/),
  reraVerified: z.boolean(),
  escrowRequired: z.boolean(),
  escrowAccount: z.object({
    bank: z.string(),
    accountNumber: z.string(),
    verified: z.boolean(),
  }).optional(),
  developerId: z.string().min(24).max(24).optional(),
  projectName: z.object({ en: z.string(), ar: z.string() }).optional(),
  status: z.enum(["draft","under_review","published","reserved","sold","rented","archived"]).optional(),
  isFeatured: z.boolean().optional(),
  isPublished: z.boolean().optional(),
  viewCount: z.number().optional(),
  favoriteCount: z.number().optional(),
  slug: z.object({ en: z.string(), ar: z.string() }).optional(),
  referenceNumber: z.string().regex(/^PROP-\d{6}$/).optional(),
  tags: z.array(z.string()).optional(),
});
